languageCode = "fr-CH"
baseurl = "https://educasuisse.ch/"
title = "Conservatoire des Arts, des Sciences et des Lettres"

[[menu.main]]
    name = "Home"
    weight = 0
    url = "/"
[[menu.main]]
    name = "À propos"
    weight = 10
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 20
    identifier = "contact"
    url = "/contact/"
